- id: broadband_adoption_households_share
  title: "Households with a broadband Internet subscription (%)"
  responsibility: "Infrastructure"
  unit: "percent"
  frequency: "annual"
  years:
    start: 2013
    end: 2023
  source:
    system: "census_acs"
    table: "B28002"
    variables:
      total_households: "B28002_001E"
      broadband_any_type: "B28002_004E"
    geography: "state:*"
    dataset: "acs/acs1"
    human_url: "https://data.census.gov/"
  denominator: "total_households"
  numerator: "broadband_any_type"
  normalize: "percent"
  comparator:
    kind: "simple_mean_other_states"
    exclude: ["HI", "DC"]
  annotations:
    - "ACS questionnaire changed in 2016; use caution comparing 2013–2015 with 2016+."
    - "ACS did not publish standard 1-year estimates for 2020; skipped or footnoted."

- id: electricity_renewables_generation_share
  title: "Renewables’ share of electricity generation (% of MWh)"
  responsibility: "Environment"
  unit: "percent"
  frequency: "annual"
  years:
    start: 2014
    end: 2023
  source:
    system: "eia"
    endpoint: "electricity/electric-power-operational-data"
    human_url: "https://www.eia.gov/opendata/browse/#/electricity"
  denominator: "total_net_generation_mwh"
  numerator: "renewable_net_generation_mwh"
  normalize: "percent"
  comparator:
    kind: "simple_mean_other_states"
    exclude: ["HI", "DC"]
  annotations:
    - "Includes small-scale solar; pumped storage excluded from numerator."

- id: public_health_uninsured_share
  title: "Uninsured rate (% of residents)"
  responsibility: "Public Health"
  unit: "percent"
  frequency: "annual"
  years:
    start: 2013
    end: 2023
  source:
    system: "census_acs"
    table: "S2701"
    variable: "S2701_C05_001"
    dataset: "acs/acs1/subject"
    human_url: "https://data.census.gov/"
  normalize: "as_is_percent"
  comparator:
    kind: "simple_mean_other_states"
    exclude: ["HI", "DC"]
  annotations:
    - "ACS 2020 1-year release is experimental; skipped or footnoted."
